module.exports = {
  content: ["./app.vue", "./{components,pages,layouts}/**/*.{vue,js,ts,jsx,tsx}"],
  darkMode: "class", // or 'media' or 'class'
  theme: {
    extend: {},
  },
  daisyui: {
    themes: [
      {
        lidark: {
          "primary": "#3daee9",
          "secondary": "#04bac5",
          "accent": "#e974a3",
          "neutral": "#31363b",
          "base-100": "#232629",
          "info": "#eff0f1",
          "success": "#2cde85",
          "warning": "#ffac33",
          "error": "#c6344a",
        },
        lidark_amoled: {
          "primary": "#3daee9",
          "secondary": "#04bac5",
          "accent": "#e974a3",
          /* neutral alternative: #31363b */
          "neutral": "#232629",
          "base-100": "#000000",
          "info": "#eff0f1",
          "success": "#2cde85",
          "warning": "#ffac33",
          "error": "#c6344a",
        },
        /* TODO */
        lilight: {
          "primary": "#3daee9",
          "secondary": "#04bac5",
          "accent": "#e974a3",
          "neutral": "#31363b",
          "base-100": "#eff0f1",
          "info": "#4d4d4d",
          "success": "#2cde85",
          "warning": "#ffac33",
          "error": "#c6344a",
        },
        homebox: {
          primary: "#5C7F67",
          secondary: "#ECF4E7",
          accent: "#FFDA56",
          neutral: "#2C2E27",
          "base-100": "#FFFFFF",
          info: "#3ABFF8",
          success: "#36D399",
          warning: "#FBBD23",
          error: "#F87272",
        },
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },
  variants: {
    extend: {},
  },
  plugins: [require("@tailwindcss/aspect-ratio"), require("@tailwindcss/typography"), require("daisyui")],
};
